# Generated by Django 5.0.1 on 2025-09-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='product',
            name='monthly',
        ),
        migrations.RemoveField(
            model_name='product',
            name='region',
        ),
    ]
