# Generated by Django 5.0.1 on 2025-09-23 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_discount_remove_product_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.duration')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='product.product')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.region')),
            ],
            options={
                'unique_together': {('product', 'region', 'duration')},
            },
        ),
    ]
