# Generated by Django 5.0.1 on 2025-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage (e.g., 20 for 20%)', max_digits=5, null=True),
        ),
    ]
