# Generated by Django 5.0.1 on 2025-09-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='activated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed')], default='UNDER_REVIEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='utr_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
