# Generated by Django 5.0.1 on 2025-09-24 13:11

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_purchase_utr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='utr_id',
            field=models.CharField(help_text='Enter a 12-digit numeric UTR ID', max_length=12, validators=[product.models.validate_utr]),
        ),
    ]
