# Generated by Django 5.0.1 on 2025-09-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_purchase_utr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Expired')], default='UNDER_REVIEW', max_length=20),
        ),
    ]
