# Generated by Django 5.0.1 on 2025-10-27 12:56

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adcampaign',
            options={'ordering': ('-id',), 'verbose_name': 'Ad Campaign', 'verbose_name_plural': 'Ad Campaigns'},
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='activated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='utr_id',
            field=models.CharField(blank=True, help_text='Enter 12-digit UTR ID after payment', max_length=12, null=True, unique=True, validators=[ads.models.validate_utr]),
        ),
        migrations.AlterField(
            model_name='adcampaign',
            name='status',
            field=models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('PAID', 'Paid'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Expired')], default='UNDER_REVIEW', max_length=20),
        ),
    ]
